version: '3.9'

services:

  # Database
  # mysql:
  #   image: mysql:latest
  #   container_name: parktify-mysql
  #   restart: always
  #   environment: 
  #     MYSQL_DATABASE: 'parktify'
  #     MYSQL_USER: 'parktify'
  #     MYSQL_PASSWORD: '1234'
  #     MYSQL_ROOT_PASSWORD: 'password'
  #   ports: 
  #     - 3306:3306
  #   expose: 
  #     - 3306
  #   volumes: 
  #     - ./data:/var/lib/mysql

  # # Cache in memory
  # redis:
  #   image: redis:latest
  #   container_name: parktify-redis
  #   restart: always
  #   ports: 
  #     - 1234:6379
  #   expose:
  #     - 1234

  # Application
  server: 
    container_name: boss-test-server
    build: .
    ports:
      - 8000:8000
    expose:
      - 8000
  

volumes:
  db_data: 